syntax on
filetype off

filetype plugin indent on
set showmode number nohlsearch
set tabstop=4
set softtabstop=0 noexpandtab
set shiftwidth=4
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab
               
nmap <C-N> :set invnumber<CR>
set background=dark
autocmd FileType yaml setlocal ai et ts=2 sw=2 cuc cul
autocmd FileType python setlocal ai et ts=4 sw=4 cuc cul
