# SPDX-License-Identifier: MIT-0
---
# defaults file for ./ansible-role-onedrive

# OneDrive package to install
onedrive_package: onedrive-abraunegg

# OneDrive sync directory name
onedrive_sync_dir: OneDrive

# OneDrive config directory name
onedrive_config_dir: .config/onedrive
