Port 45100
ListenAddress 0.0.0.0
LoginGraceTime 2m
PermitRootLogin no
StrictModes yes
MaxAuthTries 6
MaxSessions 10
PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no
TCPKeepAlive yes
ClientAliveInterval 30
ClientAliveCountMax 6
UseDNS no
AllowTcpForwarding yes
MaxStartups 10:30:100
Ciphers chacha20-poly1305@openssh.com,aes128-gcm@openssh.com
MACs hmac-sha2-256-etm@openssh.com
KexAlgorithms mlkem768x25519-sha256,sntrup761x25519-sha512@openssh.com,curve25519-sha256
Compression delayed