---
network_hostname: "{{ cached_hostname | default(ansible_hostname) | upper }}"
network_hostname_raw: "{{ cached_hostname_raw | default(ansible_hostname) }}"

network_config_hosts:
  - ASTER
  - YUGEN
  - KVM

network_wifi_ssid: esher
