# SPDX-License-Identifier: MIT-0
---
# Fallback when pipewire runs without the user role in the same play
default_group: users

users:
  - name: dvaliente
    group: users
  - name: devops
    group: users
