---
all:
  children:
    k8s_cluster:
      children:
        k8s_control_plane:
          hosts:
            k8s-mstr00:
              ansible_host: 192.168.122.216
        k8s_workers:
          hosts:
            k8s-node00:
              ansible_host: 192.168.122.139
            k8s-node01:
              ansible_host: 192.168.122.62
            k8s-node02:
              ansible_host: 192.168.122.26
