context.modules = [
  {
    name = libpipewire-module-filter-chain
    args = {
      node.description = "Soft Limiter"
      media.name       = "Soft Limiter"
      filter.graph = {
        nodes = [
          {
            type = limiter
            name = limiter
            control = {
              threshold = -1.0
              release = 50
              attack = 5
            }
          }
        ]
      }
      capture.props = {
        media.class = Audio/Sink
      }
      playback.props = {
        media.class = Audio/Source
      }
    }
  }
]