---
galaxy_info:
  author: dvaliente
  description: Configures Arch Linux OS settings including locale, mirrors, and NTP
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Archlinux
      versions:
        - all
  galaxy_tags:
    - system
    - archlinux
    - locale
    - ntp

dependencies: []
