# SPDX-License-Identifier: MIT-0
---
# tasks file for ansible-role-gerbera

- name: Create /srv/media directory
  ansible.builtin.file:
    path: /srv/docker/gerbera
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
    - gerbera
    - config

- name: Check if gerbera container already exists
  ansible.builtin.command: docker ps -a -f name=^gerbera$ --format '{{ "{{" }}.Names{{ "}}" }}'
  register: gerbera_container_check
  changed_when: false
  failed_when: false
  tags:
    - gerbera
    - docker

- name: Create and start gerbera Docker container
  ansible.builtin.shell: |
    docker run -d --name gerbera --restart=unless-stopped \
      --network=host \
      -e G_LOG=info \
      -v /srv/media:/mnt/content:ro \
      gerbera/gerbera:latest
  when: (gerbera_container_check.stdout | trim) != 'gerbera'
  tags:
    - gerbera
    - docker
