# SPDX-License-Identifier: MIT-0
---
galaxy_info:
  author: dvaliente
  description: Installs and configures OneDrive client for all users
  license: MIT-0
  min_ansible_version: "2.10"

  platforms:
    - name: Archlinux
      versions:
        - all

  galaxy_tags:
    - onedrive
    - cloud
    - sync
    - archlinux
