---
galaxy_info:
  author: dvaliente
  description: systemd-networkd, WiFi, THEMIS br0 bridge, SSH drop-in, connectivity wait
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Archlinux
      versions:
        - all
  galaxy_tags:
    - system
    - archlinux
    - network-host

dependencies: []
