# SPDX-License-Identifier: MIT-0
---
galaxy_info:
  author: dvaliente
  description: Deploys PipeWire and WirePlumber user config drop-ins
  license: MIT-0
  min_ansible_version: "2.10"

  platforms:
    - name: Archlinux
      versions:
        - all

  galaxy_tags:
    - audio
    - pipewire
    - sound
    - archlinux
