---
# Local server inventory for playbooks/server.yml.
# ansible-playbook playbooks/server.yml -i inventories/server/hosts.yml
all:
  children:
    servers:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
